version: '3'
services:
  primary:
    build: .
    ports:
    - "8080:8080"
    links:
    - verificationone
    - verificationtwo
  verificationone:
    build:
      context: .
      dockerfile: Dockerfile.verification
    environment:
    - VERIFY_PORT=8080
    ports:
    - "8081:8080"
  verificationtwo:
    build: 
      context: .
      dockerfile: Dockerfile.verification
    environment:
    - VERIFY_PORT=8080
    ports:
    - "8082:8080"